name: video_editor
version: 2.4.1
publish_to: none
environment:
  flutter: ">=3.0.0"
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_video_player: ^2.0.4
  path: ^1.9.0
  path_provider: ^2.1.2
  transparent_image: ^2.0.1
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

