name: video_editor
version: 3.0.0
description: |
  A flutter package for editing video with fully customizable UI.
  Supports crop, trim, rotation and cover selection.
  Provides commands to run in order to export the video or cover.
publish_to: "none"
#repository: https://github.com/LeGoffMael/video_editor

environment:
  sdk: ">=2.19.6 <4.0.0"
  flutter: ">=3.10.0 <3.10.4"

dependencies:
  flutter:
    sdk: flutter

  cached_video_player: ^2.0.4
  path: ^1.8.3
  path_provider: ^2.0.15
  transparent_image: ^2.0.1
  video_compress: ^3.1.2
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

# screenshots:
#   - description: "Video editor demo"
#     path: assets/demo_thumb.webp
